In [13]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: numpy in c:\python312\lib\site-packages (2.0.0)




[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import numpy
a=numpy.array([0,1,2,3,4])
print(a)
print(type(a))




[0 1 2 3 4]
<class 'numpy.ndarray'>


In [15]:
b=numpy.array(10)
print(b)

10


In [16]:


f=numpy.array([[1,2,3,4],[5,6,7,8] ])
print(f)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
# ndim using for identify which dimensional (1,2 or 3)

k=numpy.array ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])                               
print(k)
print(k.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [18]:
a=numpy.array([1,2,3,4],ndmin=5)
print(a)
print(a.ndim)



[[[[[1 2 3 4]]]]]
5


In [19]:
a=numpy.array([1,2,3,4])
print(a[0]+a[2])




4


In [20]:
a=numpy.array([[1,2,3,4],[5,6,7,8]])
print(a[0,3])

4


In [21]:
a=numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a[1,1,1])

11


In [22]:
a=numpy.array([1,2,3,4,5,6])
b=a[1:5]
print(b)

[2 3 4 5]


In [23]:
a=numpy.array([[1,2,3,4],[5,6,7,8]])
b=a[1,1:4]
print(b)

[6 7 8]


In [24]:
a=numpy.array([[[1,2,3,7,8],[4,5,6,6,8]],[[7,8,9,5,7],[10,11,12,13,16]]])
b=a[1,1,1:4]
print(b)

[11 12 13]


In [25]:
# numpy.zeross

array=numpy.zeros(5)
print(array)

[0. 0. 0. 0. 0.]


In [26]:
# numpy.ones:

array=numpy.ones((4,3))
print(array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# numpy arrange


array=numpy.arange(10,20)
print(array)

[10 11 12 13 14 15 16 17 18 19]


In [28]:
array=numpy.arange(20,51,2)
print(array)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [29]:
# numpy.linspace    split 1 t0 10 vare ullathil value 5 vech split cheythu

array=numpy.linspace(1,10,5)
print(array)

[ 1.    3.25  5.5   7.75 10.  ]


In [30]:
array=numpy.eye(10)
print(array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [31]:
# numpy.eye

array=numpy.eye(10)
print(array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [32]:
# numpy.randomm  0 to 100 vare ulladhil values 5 vech split cheythu varunnu like linspace:-

array=numpy.random.randint(0,100,5)
print(array)

[59 29 71 41 56]


In [33]:
# numpy.random.randomm

# array=numpy.random.random(100)  100  point values between 0 to 1 
print(array)

[59 29 71 41 56]


In [34]:
# shape function 1 dimensional  (numbers of the list)

import numpy as  np
array=numpy.array([1,2,10])
print(array)
print(array.shape)


[ 1  2 10]
(3,)


In [35]:
# shape function 2 dimensional  (2 dimension,and oroonnilum 4 numbers)


import numpy as np
array=numpy.array([[2,3,4,5],[6,7,8,9]])
print(array)
print(array.shape)

[[2 3 4 5]
 [6 7 8 9]]
(2, 4)


In [74]:
# shape function 3 dimensional  (2 list varunnu,,,oro listlum 2 list vere ennam nd,,,,,,,athilulla numbers )

import numpy as np
array=numpy.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(array)
print(array.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
(2, 2, 4)


In [37]:
# reshape function using the number of columns and raws


import numpy as np
array=numpy.array([1,2,3,4,5,6])
print(array.reshape (2,3))


[[1 2 3]
 [4 5 6]]


In [38]:
# convert array in 3 dimension into 2    reshape use to convert

import numpy as np
array=numpy.array([[[1,2,3],[5,6,7]],[[9,10,11],[13,14,15]]])
array2=array.reshape(6,2)
print(array2)



[[ 1  2]
 [ 3  5]
 [ 6  7]
 [ 9 10]
 [11 13]
 [14 15]]


In [39]:
# concatenate  1D:-  (COMBINE ARRAY)
a=numpy.array([1,2,3,4])
b=numpy.array([5,6,7,8])
result=numpy.concatenate((a,b))
print(result)


[1 2 3 4 5 6 7 8]


In [40]:
# concatenate 2D

a=numpy.array([[1,2,3],[4,5,6]])
b=numpy.array([[7,8,9],[10,11,12]])
result=numpy.concatenate((a,b))

print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
# STACK USING COMBINE:

a=numpy.array([[1,2,3],[4,5,6]])
b=numpy.array([[7,8,9],[10,11,12]])
result=numpy.stack((a,b))
print(result)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [42]:
# HSTACK ALSO COMBINE:-  2D  (horizondal)

a=numpy.array([[1,2,3],[4,5,6]])
b=numpy.array([[7,8,9],[10,11,12]])
result=numpy.hstack((a,b))
print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [43]:
# VSTACK ALSO COMBINE  2D   (vertically)

a=numpy.array([[1,2,3],[4,5,6]])
b=numpy.array([[7,8,9],[10,11,12]])
result=numpy.vstack((a,b))
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [44]:
# DSTACK ALSO COMBINE   2D (depth wise)

a=numpy.array([[1,2,3],[4,5,6]])
b=numpy.array([[7,8,9],[10,11,12]])
result=numpy.dstack((a,b))
print(result)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [45]:
import numpy as np
array=numpy.array([[1,2,3,],[4,5,6]])
print(array.reshape(1,2,3))

[[[1 2 3]
  [4 5 6]]]


In [46]:
# split function in 1D:-


array=([1,2,3,4,5,6])
result=numpy.array_split (array,3)
print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [47]:
# SPLIT FUNCTION IN 2D:-

array=([[1,2,3,4],[5,6,7,8]])
result=numpy.array_split(array,3)
print(result)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int64)]


In [48]:
# SPLIT FUNCTION 3D:-

array=([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
result=numpy.array_split(array,3)
print(result)

[array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]]), array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]]]), array([], shape=(0, 2, 4), dtype=int64)]


In [49]:
# 2 TO 10 LIST 3*3 METRIX:-

array=numpy.arange(2,11)
print(array.reshape(3,3))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [50]:
# FIND UNIQUE ELEMENT OF THE ARRAY:- USE (unique())

array=numpy.array([1,2,3,3,4,2])
result=numpy.unique(array)
print(result)


[1 2 3 4]


In [51]:
# union of two numbers in  2 arrays:-   (USE (union1d) 

array1=([1,2,3,4])
array2=([6,7,8,9])
result=numpy.union1d(array1,array2)
print(result)

[1 2 3 4 6 7 8 9]


In [52]:
array=numpy.random.randint(0,10)
print(array)

6


In [53]:
# DIAGNAL VALUES (4,5,6,8) ONLY print   (UDSING  (diag)

array=numpy.array([4,5,6,8])
print(array)
result=numpy.diag(array)
print(result)


[4 5 6 8]
[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [54]:
#  (6 NULL VALUE LIST OF 0 AND PRINT 6 TH POSITION =9):-

array=numpy.zeros([6])
array[5]= 9
print(array)

[0. 0. 0. 0. 0. 9.]


In [55]:
# PRINT 12 TO 39 USING ARANGE FUNCTION:-

array=numpy.arange(12,40)
print(array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39]


In [56]:
# REVERSE THE LIST OF ARRAY:-

array=numpy.array([1,2,3,4,5])
array2=array[::-1]
print(array)
print(array2)

[1 2 3 4 5]
[5 4 3 2 1]


In [57]:
# 2D ARRAY (SIZE 2*3)  (4 BYTE INT) AND PRINT (SHAPE,TYPE,DATATYPE):-

array=numpy.empty((2,3),dtype=numpy.int32)
print(array.shape)
print(type(array))
print(array.dtype)

(2, 3)
<class 'numpy.ndarray'>
int32


In [58]:
# CONVERT ARRAY TO FLOAT:-

array=numpy.array([1,2,3,4,5])
float_array=array.astype(float)
print(array)
print(float_array)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [59]:
# 8*8 MATRIX FILLED WITH ZEROS:- print (010101)


array=numpy.zeros((8,8),dtype=int)
print(array)
array[1::2, ::2]=1
array[::2 , 1::2]=1
print(array)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [60]:
# CONVERT VALUES CENTIGRADE INTO FAHRENHEINT DEGREES:-

array=numpy.array([10,20,30,40])
fahrenheit_values= array * 9/5+32
print(array)
print(fahrenheit_values)


[10 20 30 40]
[ 50.  68.  86. 104.]


In [66]:
# FIND NUMBER OF ELEMENT OF AN ARRAY,LENGTH ARRAY IN BYTES AND TOTAL BYTES CONSUMED BY ELEMENTS:-

array=numpy.array([1,2,3,4,5],dtype=numpy.int32)
num_elements=array.size
size=array.itemsize
total_bytes=array.nbytes
print(num_elements)
print(size)
print(total_bytes)

5
4
20


In [73]:
# TEST WHEATHER ELEMENT A 1D ALSO PRESENT SECOND ARRAY:-

array1=numpy.array([0,10,20,30,40])
array2=numpy.array([0,5,10,15,20])
result=numpy.in1d(array1,array2)
print(array1)
print(array2)
print(result)

[ 0 10 20 30 40]
[ 0  5 10 15 20]
[ True  True  True False False]


C:\Users\SHAMNA SHERIN\AppData\Local\Temp\ipykernel_9444\2942596897.py:5: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  result=numpy.in1d(array1,array2)


In [63]:
# FIND commoN VALUES BETWEEN 2 ARRAYS:-

array1=numpy.array([1,2,3,4,5])
array2=numpy.array([4,5,6,7,8])
common_values=numpy.intersect1d(array1,array2)
print(common_values)
print(array1)
print(array2)

[4 5]
[1 2 3 4 5]
[4 5 6 7 8]


In [67]:
array=numpy.array([1,2,3,4,5])
elements=array.size
length=array.itemsize
total_bytes=array.nbytes
print(array)
print(elements)
print(length)
print(total_bytes)

[1 2 3 4 5]
5
8
40


In [68]:
# IDENTIFY SAME VALUES:- GIVE TRUE OR FALSE

array=numpy.array([1,2,3,4])
array2=numpy.array([3,4,5,6])
a=numpy.in1d(array,array2)
print(array)
print(array2)
print(a)

[1 2 3 4]
[3 4 5 6]
[False False  True  True]


C:\Users\SHAMNA SHERIN\AppData\Local\Temp\ipykernel_9444\3342014793.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  a=numpy.in1d(array,array2)


In [69]:
# REMOVE 1,5,6 ELEMENTS:=

array=numpy.array([10,20,30,40,50,60,70,80,90,100])
b=[0,4,5]
c=numpy.delete(array,b)
print(array)
print(b)
print(c)

[ 10  20  30  40  50  60  70  80  90 100]
[0, 4, 5]
[ 20  30  40  70  80  90 100]


In [70]:
# REPLACE NEGATIVE VALUES INTO 0:-

array=numpy.array([-1,-4,0,2,3,4,5,-6])
array[array<0]=0
print(array)

[0 0 0 2 3 4 5 0]


In [71]:
# COUNT THE SPECIFIC GIVEN NUMBER:-

array=numpy.array([10,20,20,20,20,0,20,30,30,30,0,0,20,20,0])
a=20
b=numpy.count_nonzero(array==a)
print(array)
print(a)
print(b)

[10 20 20 20 20  0 20 30 30 30  0  0 20 20  0]
20
7
